name: "Relatório de bug"
description: Relate um bug para o projeto.
title: "[Bug]: "
body:
  - type: markdown
    attributes:
      value: |
        ## 🐞 Relatório de bug
        Use o formulário abaixo para relatar um bug no projeto.
  - type: textarea
    id: description
    attributes:
      label: Descrição
      description: Descreva com detalhes o bug que você encontrou.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Passos para reproduzir
      description: Descreva os passos necessários para reproduzir o bug.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Comportamento esperado
      description: Descreva o que você esperava que acontecesse.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Capturas de tela
      description: Se possível, adicione capturas de tela para ajudar a explicar o bug.
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: Ambiente
      description: Informe o sistema operacional, a versão do navegador e outras informações relevantes.
    validations:
      required: true
