name: "bug: 🐛 Relatar um bug"
description: Relate um bug para o projeto.
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        ## Obrigado por relatar um bug!
        Antes de enviar o relatório, [verifique se o bug já não foi relatado anteriormente][bugs]. Se você encontrar um relatório semelhante, adicione um comentário com detalhes adicionais para ajudar a resolver o problema.
        
        Para nos ajudar a resolver o problema, forneça o máximo de informações possível. Isso inclui detalhes sobre o ambiente em que o bug foi encontrado, passos para reproduzir o bug e qualquer outra informação relevante.
        
        [bugs]: ../../issues?q=is%3Aissue+is%3Aopen+label%3Abug
  - type: textarea
    id: description
    attributes:
      label: Descrição
