name: "docs: 📚 Solicitação de documentação"
description: Solicite uma melhoria ou adição à documentação do projeto.
labels:
  - documentation
body:
  - type: textarea
    id: description
    attributes:
      label: Descrição
