name: "feature: 🚀 Nova funcionalidade ou melhoria"
description: Solicite uma nova funcionalidade ou melhoria para o projeto.
labels:
  - enhancement
body:
  - type: textarea
    id: description
    attributes:
      label: Descrição
